CREATE TABLE READER 
(
	RID INT PRIMARY KEY,
	RNAME VARCHAR(64) NOT NULL,
	RPWD VARCHAR(64) NOT NULL,
	RSEX CHAR(2) NOT NULL
)

CREATE TABLE [ADMIN]
(
	AID INT PRIMARY KEY,
	ANAME VARCHAR(64) NOT NULL,
	APWD  VARCHAR(64) NOT NULL,
	ASEX CHAR(2) NOT NULL
)

CREATE TABLE BOOK
(
	BID INT  PRIMARY KEY,
	BNAME VARCHAR(64) NOT NULL,
	BAUTHOR VARCHAR(64) NOT NULL,
	BPRESS VARCHAR(64) NOT NULL,
	BTYPE VARCHAR(64),
	BPRICE INT NOT NULL,
	BLOCATION VARCHAR(64) NOT NULL,
	BFREE CHAR(2) NOT NULL,
	BUNSHELVE CHAR(2) NOT NULL
)

CREATE TABLE BORROW
(
	BID INT PRIMARY KEY,
	RID INT FOREIGN KEY REFERENCES READER(RID),  
	BOOKID INT FOREIGN KEY REFERENCES BOOK(BID),
	STARTTIME DATE NOT NULL,
	ENDTIME DATE NOT NULL,
	[RETURN] CHAR(2) NOT NULL
)

CREATE TABLE PULISH
(
	BID INT,
	OVERTIME CHAR(2) NOT NULL,
	[DAY] INT,
	BROKEN CHAR(2) NOT NULL,
	PAID CHAR(2) NOT NULL,
	PRIMARY KEY (BID),
	FOREIGN KEY (BID) REFERENCES BORROW(BID)
)
