USE		Lab2;
CREATE TABLE [USER]
(
	UID INT ,
	 NAME  VARCHAR(64),
	 SEX  CHAR(2) ,
	 BYEAR  INT,
	 CITY  VARCHAR(64),
	PRIMARY KEY(UID)
);

CREATE TABLE  LABEL 
(
	 LID  INT,
	 LNAME  VARCHAR(64)
	PRIMARY KEY  (LID)
);

CREATE TABLE  MBLOG 
(
	 BID  INT,
	 TITLE   VARCHAR(128),
	 UID  INT ,
	 PYEAR  INT,
	 PMONTH  INT,
	 PDAY  INT ,
	 CONT  VARCHAR(1024),
	PRIMARY KEY  (BID),
	FOREIGN  KEY  (UID)  REFERENCES  [USER] (UID)
);

CREATE TABLE  B_L 
(
	 BID  INT ,
	 LID  INT,
	PRIMARY KEY ( BID , LID ),
	FOREIGN KEY  (BID)  REFERENCES  MBLOG (BID) ,
	FOREIGN KEY  (LID)  REFERENCES  LABEL(LID) 
);

CREATE TABLE  FOLLOW 
(
	 UID  INT,
	 UIDFLED  INT,
	PRIMARY KEY ( UID , UIDFLED ),
	FOREIGN KEY  (UID)  REFERENCES  [USER](UID), 
	FOREIGN KEY  (UIDFLED)  REFERENCES  [USER] (UID) 
);

CREATE TABLE  FRIENDS 
(
	 UID  INT,
	 FUID  INT,
	PRIMARY KEY ( UID , FUID ),
	FOREIGN KEY  (UID)  REFERENCES  [USER] (UID) ,
	FOREIGN KEY  (FUID)  REFERENCES  [USER] (UID) 
);

CREATE TABLE  SUB 
(
	 UID  INT,
	 LID  INT,
	PRIMARY KEY ( UID , LID ),
	FOREIGN KEY  (UID)  REFERENCES  [USER] (UID) ,
	FOREIGN KEY  (LID)  REFERENCES  [LABEL](LID) 
);

CREATE TABLE  THUMB 
(
	 UID  INT,
	 BID  INT,
	PRIMARY KEY ( UID , BID ),
	FOREIGN KEY  (UID)  REFERENCES  [USER](UID) ,
	FOREIGN KEY  (BID)  REFERENCES  [MBLOG](BID) 
);

CREATE TABLE  TOPDAY 
(
	 TYEAR  INT,
	 TMONTH  INT,
	 TDAY  INT,
	 BID  INT,
	 TNO  INT,
	PRIMARY KEY ( TYEAR , TMONTH , TDAY , BID ),
	FOREIGN KEY  (BID)  REFERENCES  [MBLOG](BID)
);