CREATE TABLE  TESTPRIMARYKEY
(
	[UID] INT,
	[NAME] VARCHAR(64)
);

INSERT INTO TESTPRIMARYKEY
VALUES (1,'TOM');

INSERT INTO TESTPRIMARYKEY
VALUES (1,'TOM');

INSERT INTO TESTPRIMARYKEY
VALUES(2,'JERRY');

INSERT INTO TESTPRIMARYKEY
VALUES(3,'DEVICE');