/*
SELECT DISTINCT [UID]
FROM SUB 
WHERE LID IN 
(
	SELECT LID 
	FROM LABEL
	WHERE LNAME = '文学'
	OR LNAME = '艺术' 
	OR LNAME = '哲学'
	OR LNAME = '音乐'
)
*/

SELECT DISTINCT [UID]
FROM SUB,LABEL
WHERE LABEL.LID = SUB.LID
AND LABEL.LNAME IN ('文学','艺术','哲学','音乐')